### ISSUE TITLE
Transport weight

### ISSUE THREAD

**Issue by mosemister** [ColonelKai/PublicTransit#18]
When transporting on a line a player must be holding a select amount of items or lower to transport. This weight value should have a global default specified in the config file but each line may overwrite this value. 

If a line does not overwrite this value and the config value changes, then the weight value should change too

- [x] create a config value for weight enabled of a boolean (default true)
- [x] create a config value for weight of a integer (default value of 500)
- [x] create a nullable integer of weight in the Line (if null then read config value when getting the value)
- weight is calculated based on all items in the players inventory plus the items stack size
- [x] write tests

**Comment by ColonelKai** [comment]
Either add an additional boolean config value to remove this system or make it so that negative values disable the system. 

I want this to be a disable-able module.

**Comment by mosemister** [comment]
Ah shoot yes forgot that requirement. I personally dont like magic values even in configs so ill go with a ``enabled`` boolean

**Comment by ColonelKai** [comment]
Alright, either works for me. I want maximum customisability for my plugins.
