### ISSUE TITLE
Writing Commands

### ISSUE THREAD

**Issue by ColonelKai** [ColonelKai/PublicTransit#8]
##**Player Commands**

- [x] `/travel <startingnode> <endingnode>`
Travels a player on the line, starting node argument should be suggest the nearby nodes, and then once a starting node is chosen, the available ending nodes from that starting node should be suggested. @mosemister Can we make the second argument of a command suggest based on the first argument? If not, we will just suggest all available nodes from all nearby nodes.

- [x] `/publictransit info <line> [index]`
Lists all relevant information on the stop/line. When the line is provided, the second argument (marked as index) will be available both as names for stops and indexes for all nodes.   

- [x] `/publictransit cost <start node> <end node>`
Returns the price of traveling between the said nodes.

##**Admin Commands**

### Line
- [x] `/publictransit createline <linename>`
Creates a new line. The values like cost, costType, direction etc shall be loaded from the config as the default value. 

- [x] `/publictransit setlineoption <option> <value>`
Changes options of a line like  cost, name, costType, direction etc...

- [x] `/publictransit deleteline <linename> [linename again for confirmation]`
Delete a line. We will use the classic cheap confirmation method of a second arg.

### Node
- [x] `/publictransit createnode stop <linename> [nodePrice]`
Creates a new node. Location is set to the location of the player. 

- [x] `/publictransit createnode transitional <linename> [nodePrice]`
Creates a new node. Location is set to the location of the player. 

- [x] `/publictransit setnodeoption <option> <value>`
Changes options of a node like location, name, nodetype, time...

- [x] `/publictransit deletenode <linename><index> [nodename again for confirmation]`
Delete a node. We will use the classic cheap confirmation method of a second arg.

- [x] `/publictransit movenode <oldlinename> <oldindex> <newlinename> <newindex>`
Moves a node. The line could be the same. When removed, all indexes larger than node should be lowered by 1. When added, opposite. I think this is how indexes work in java anyway.

- [x] `/publictransit clonenode <oldlinename> <oldindex> <newlinename> <newindex>`
Clones a node. Same as above, except the old one stays.

**Comment by mosemister** [comment]
## Answer to your question
You can make arguments react based on the current arguments specified (react being suggestions and acceptable inputs as long as the type doesnt change (if the type needs to change then register another command with the other argument type)). Its a bit strange on how to do it and the argument type itself needs to support it, but that can easily be done for these commands.

## Small issue

As mentioned before A ``Stop`` node must have a name, while a ``Transitional`` node doesn't (or might do?). For the creation of the node you have specified that the name is required. It maybe better having it as two different commands

``/pt node create stop <line name> <node index> <node name>``
``/pt node create transitional <line name> <node index>``

(could shorten stop and transitional to ``s`` and ``t`` as alternatives)
Also why isnt the price specified in this command as a optional?

## Consistancy

This is more of a note, more then happy if you ignore it

consistancy reasons i would rather the commands be structured by sub category so the following would be the commands

``/pt travel [line name] [starting node name] <ending node name>``
``/pt info [line name] [node name/index ...]``
``/pt cost [line name] [node name/index] [node name/index]``
``/pt line create <line name>``
``/pt line option set <option> <value>``
``/pt line delete <line name> <confirm name>``
``/pt  node create <line name> <node index> <node name> [cost type] [cost]``
``/pt node option set <option> <value>``
``/pt node delete <line name> <node name/index> <node name/index>``
``/pt node move <old line name> <old node name/index> [new line name] <new node index>``
``pt node clone <old line name> <old node name/index> [new line name] <new node index>``

or another category would be reversing the sub cateogry of sub cateogry, so something like

``pt create line <line name>``
``pt create node stop <line name> <node index> <node name>``
``pt delete line <line name> <confirm name>``
etc...

Just a though

**Comment by mosemister** [comment]
Got a pull request in draft that will help with this issue no matter what you choose

https://github.com/ColonelKai/PublicTransit/pull/10

Just finishing off the tests before its ready, but if you want to merge it into your local branch for these commands then do so

Need to finish the tests for
- suggestions of lines
- suggestions of nodes
- parsing nodes

**Comment by ColonelKai** [comment]
> As mentioned before A `Stop` node must have a name, while a `Transitional` node doesn't (or might do?). For the creation of the node you have specified that the name is required. It maybe better having it as two different comands

You are correct. We should make two separate commands. I will edit it momentarily.

**Comment by ColonelKai** [comment]
> consistancy reasons i would rather the commands be structured by sub category so the following would be the commands

The reason why I didn't do it is because I've used both before, but the system of not having a subcategory (like dmarker) has won out for me for osme reason. Its just more convenient seeing all the options I guess.

**Comment by mosemister** [comment]
> > consistancy reasons i would rather the commands be structured by sub category so the following would be the commands
> 
> The reason why I didn't do it is because I've used both before, but the system of not having a subcategory (like dmarker) has won out for me for osme reason. Its just more convenient seeing all the options I guess.

Sorry just seen this. 
In my experience, most users get overwelmed if you provide everything at once in a big list. Especially if you have more ... fined tuned commands which can lead to a experience such as Bukkits ``Materials`` list where even a developer has no idea what are items or blocks in that list

**Comment by ColonelKai** [comment]
Hmm sure, let's do it your way, my method was only coming from my own experience - since you're more experienced and have dealt with more users, I'll take your word for it.
